name: Joris Swinkels
favicon: null
layout_spectrum: 0.53088
typography_spectrum: 0.1612903
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Transformational Trainer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#565401'
    - '#c7bf6e'
    - '#96964c'
    - '#253801'
    - '#ebfbdd'
  brandStrength: 0.1875
  lightness: 0
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
