layout_spectrum: 0.059458683244884014
typography_spectrum: 0.8695380985736847
color:
  brandColors:
    - '#FFFFFF'
    - '#1582EF'
    - '#FC2F2D'
    - '#252525'
    - '#71CCFB'
  brandStrength: 0.7748338768724352
  lightness: 0.3528968854807317
  saturation: 0.8201438060496002
  rhythmicContrast: 0.030067233135923743
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-74351104-1
  facebook: null
  twitter: null
name: Joris Swinkels
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Who are we?
    id: 75d05a40-9a51-4ded-97d0-0d4a52f51a1c
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Waking up the World
description: the new generation of Life and Business is Teal
purpose: []
