layout_spectrum: 0.7770816893316805
typography_spectrum: 0.8292943453416228
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.21635144692845643
  lightness: 0.8223274990450591
  saturation: 0.6092058741487563
  rhythmicContrast: 0.9560982310213149
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-74351104-1
  facebook: null
  twitter: null
name: Joris Swinkels
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Joris
    id: 6635de80-c376-40bf-a809-c181d9c82b68
    type: content
  - name: CCI
    id: 49e11aa3-6bbc-49de-a012-173eabad6971
    type: content
  - name: Contact
    id: 3fddf00e-a91e-4122-a0ba-e1f0888c00c7
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Waking up the World
description: the new generation of Life and Business is Teal
purpose: []
