analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 1
title: Are you Living the Life you Love to Live?
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.25
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#716f6e'
    - '#e20a16'
    - '#d8d9d7'
    - '#000000'
    - '#0000ff'
  lightness: 0.25
purpose: []
favicon: null
name: Joris Swinkels
typography_spectrum: 0
