name: Joris Swinkels
favicon: null
layout_spectrum: 0.9516129
typography_spectrum: 0.1612903
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Professional Trainer and Transformational Coaching
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dbc6ab'
    - '#ffffff'
    - '#cf7d19'
    - '#562300'
  brandStrength: 0.3655914
  lightness: 0.3763441
  saturation: 1
  rhythmicContrast: 0.7114695
purpose: []
