name: Joris Swinkels
favicon: null
layout_spectrum: 0.50825
typography_spectrum: 0
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Joris Swinkels
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#716f6e'
    - '#e20a16'
    - '#d8d9d7'
    - '#000000'
    - '#0000ff'
  brandStrength: 1
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 1
purpose: []
