typography_spectrum: 0.2429
color:
  brandColors:
    - '#F2FAFC'
    - '#A2BD30'
    - '#ABD8FA'
    - '#1F65D0'
    - '#07392A'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74541
analytics:
  google: UA-74351104-1
  facebook: null
  twitter: null
name: Joris Swinkels
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Waking up the World
description: the new generation of Life and Business is Teal
purpose: []
